package ihsinformatics.com.hydra_mobile.utils

enum class InputWidgetsType {
    WIDGET_TYPE_DATE,
    WIDGET_TYPE_TEXT_BOX,
    WIDGET_TYPE_SPINNER,
    WIDGET_TYPE_SCORE_SPINNER,
    WIDGET_TYPE_MULTI_SELECT_SPINNER,
    WIDGET_TYPE_RADIO_BUTTON,
    WIDGET_TYPE_CHECK_BOX,
    WIDGET_TYPE_HEADING,
    WIDGET_TYPE_GPS,
    WIDGET_TYPE_HIDDEN_INPUT,
    WIDGET_TYPE_AGE,
    WIDGET_TYPE_IMAGE,
    WIDGETS_TYPE_SINGLE_SELECT_EDITTEXT,
    WIDGETS_TYPE_SINGLE_SELECT_TEXTVIEW,
    WIDGETS_TYPE_QR_READER,
    WIDGETS_TYPE_AUTOCOMPLETE_EDITTEXT,
    WIDGET_TYPE_ADDRESS
}