package com.ihsinformatics.dynamicformsgenerator.data.pojos;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "IDENTIFIER_TYPE".
*/
public class IdentifierTypeDao extends AbstractDao<IdentifierType, Long> {

    public static final String TABLENAME = "IDENTIFIER_TYPE";

    /**
     * Properties of entity IdentifierType.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "_id");
        public final static Property TypeName = new Property(1, String.class, "typeName", false, "TYPE_NAME");
    }


    public IdentifierTypeDao(DaoConfig config) {
        super(config);
    }
    
    public IdentifierTypeDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"IDENTIFIER_TYPE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL ," + // 0: id
                "\"TYPE_NAME\" TEXT NOT NULL );"); // 1: typeName
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"IDENTIFIER_TYPE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, IdentifierType entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
        stmt.bindString(2, entity.getTypeName());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, IdentifierType entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
        stmt.bindString(2, entity.getTypeName());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public IdentifierType readEntity(Cursor cursor, int offset) {
        IdentifierType entity = new IdentifierType( //
            cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1) // typeName
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, IdentifierType entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setTypeName(cursor.getString(offset + 1));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(IdentifierType entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(IdentifierType entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(IdentifierType entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
