package com.ihsinformatics.dynamicformsgenerator.data.pojos;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.ihsinformatics.dynamicformsgenerator.data.database.DaoSession;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "LOCATION_ATTRIBUTE".
*/
public class LocationAttributeDao extends AbstractDao<LocationAttribute, Long> {

    public static final String TABLENAME = "LOCATION_ATTRIBUTE";

    /**
     * Properties of entity LocationAttribute.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Value = new Property(1, String.class, "value", false, "VALUE");
        public final static Property Uuid = new Property(2, String.class, "uuid", false, "UUID");
        public final static Property LocationId = new Property(3, Long.class, "locationId", false, "LOCATION_ID");
        public final static Property LocationAttributeTypeId = new Property(4, Long.class, "locationAttributeTypeId", false, "LOCATION_ATTRIBUTE_TYPE_ID");
    }

    private DaoSession daoSession;


    public LocationAttributeDao(DaoConfig config) {
        super(config);
    }
    
    public LocationAttributeDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"LOCATION_ATTRIBUTE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"VALUE\" TEXT," + // 1: value
                "\"UUID\" TEXT UNIQUE ," + // 2: uuid
                "\"LOCATION_ID\" INTEGER," + // 3: locationId
                "\"LOCATION_ATTRIBUTE_TYPE_ID\" INTEGER);"); // 4: locationAttributeTypeId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"LOCATION_ATTRIBUTE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, LocationAttribute entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String value = entity.getValue();
        if (value != null) {
            stmt.bindString(2, value);
        }
 
        String uuid = entity.getUuid();
        if (uuid != null) {
            stmt.bindString(3, uuid);
        }
 
        Long locationId = entity.getLocationId();
        if (locationId != null) {
            stmt.bindLong(4, locationId);
        }
 
        Long locationAttributeTypeId = entity.getLocationAttributeTypeId();
        if (locationAttributeTypeId != null) {
            stmt.bindLong(5, locationAttributeTypeId);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, LocationAttribute entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String value = entity.getValue();
        if (value != null) {
            stmt.bindString(2, value);
        }
 
        String uuid = entity.getUuid();
        if (uuid != null) {
            stmt.bindString(3, uuid);
        }
 
        Long locationId = entity.getLocationId();
        if (locationId != null) {
            stmt.bindLong(4, locationId);
        }
 
        Long locationAttributeTypeId = entity.getLocationAttributeTypeId();
        if (locationAttributeTypeId != null) {
            stmt.bindLong(5, locationAttributeTypeId);
        }
    }

    @Override
    protected final void attachEntity(LocationAttribute entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public LocationAttribute readEntity(Cursor cursor, int offset) {
        LocationAttribute entity = new LocationAttribute( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // value
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // uuid
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3), // locationId
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4) // locationAttributeTypeId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, LocationAttribute entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setValue(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setUuid(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setLocationId(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
        entity.setLocationAttributeTypeId(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(LocationAttribute entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(LocationAttribute entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(LocationAttribute entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getLocationDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getLocationAttributeTypeDao().getAllColumns());
            builder.append(" FROM LOCATION_ATTRIBUTE T");
            builder.append(" LEFT JOIN LOCATION T0 ON T.\"LOCATION_ID\"=T0.\"_id\"");
            builder.append(" LEFT JOIN LOCATION_ATTRIBUTE_TYPE T1 ON T.\"LOCATION_ATTRIBUTE_TYPE_ID\"=T1.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected LocationAttribute loadCurrentDeep(Cursor cursor, boolean lock) {
        LocationAttribute entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Location location = loadCurrentOther(daoSession.getLocationDao(), cursor, offset);
        entity.setLocation(location);
        offset += daoSession.getLocationDao().getAllColumns().length;

        LocationAttributeType locationAttributeType = loadCurrentOther(daoSession.getLocationAttributeTypeDao(), cursor, offset);
        entity.setLocationAttributeType(locationAttributeType);

        return entity;    
    }

    public LocationAttribute loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<LocationAttribute> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<LocationAttribute> list = new ArrayList<LocationAttribute>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<LocationAttribute> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<LocationAttribute> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
